In [6]:
import numpy as np

## Data Types and Attributes

In [7]:
# numpy’s main data structure is ndarray (N-dimensional array). It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

numbers_1 = np.array([1,2,3,4,5,6])
numbers_1

array([1, 2, 3, 4, 5, 6])

In [8]:
type(numbers_1)

numpy.ndarray

In [9]:
numbers_2 = np.array([[1,2,3],[4,5,6]])
numbers_3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [10]:
numbers_2.shape

(2, 3)

In [11]:
numbers_3.shape

(2, 2, 3)

In [12]:
numbers_1.ndim, numbers_2.ndim, numbers_3.ndim

(1, 2, 3)

In [13]:
numbers_1

array([1, 2, 3, 4, 5, 6])

In [14]:
numbers_2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
numbers_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
# Create DataFrame from numpy array
import pandas as pd

In [17]:
df = pd.DataFrame(numbers_2)
df

   0  1  2
0  1  2  3
1  4  5  6

## Creating a numpy array

In [18]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
type(zeros)

numpy.ndarray

In [21]:
zeros.dtype

dtype('float64')

In [22]:
ones.dtype

dtype('float64')

In [23]:
arrange_array = np.arange(0,10, 2) 
arrange_array

array([0, 2, 4, 6, 8])

In [24]:
random_array_0 = np.random.randint(0,10, size=(4,4))
random_array_0

array([[6, 6, 9, 4],
       [0, 0, 4, 3],
       [8, 8, 1, 1],
       [1, 4, 1, 8]], dtype=int32)

In [25]:
type(random_array_0)

numpy.ndarray

In [26]:
random_array_1 = np.random.random((3,4))
random_array_1

array([[0.19500535, 0.34990893, 0.52144682, 0.70286153],
       [0.04422008, 0.71441245, 0.48002876, 0.26940745],
       [0.09555659, 0.70597583, 0.51271448, 0.58924273]])

In [27]:
random_array_2 = np.random.rand

In [28]:
random_array_2 = np.random.rand(3,4)
random_array_2

array([[0.22618254, 0.65732607, 0.31309832, 0.16486296],
       [0.85076493, 0.4936033 , 0.17208338, 0.6554705 ],
       [0.47886791, 0.59316341, 0.7068921 , 0.85685299]])

## Manipulating and Comparing Arrays

### Arithmetic Operations

In [29]:
numbers_1

array([1, 2, 3, 4, 5, 6])

In [30]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
ones = np.ones(6)
ones

array([1., 1., 1., 1., 1., 1.])

In [32]:
numbers_1 + ones

array([2., 3., 4., 5., 6., 7.])

In [33]:
np.add(numbers_1, ones)

array([2., 3., 4., 5., 6., 7.])

In [34]:
ones*numbers_1

array([1., 2., 3., 4., 5., 6.])

In [35]:
numbers_2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
ones = np.ones(3)

In [37]:
numbers_2*ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
numbers_2 / ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
numbers_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
numbers_2

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# Floor Division (This removes the decimal and round he figure up)
numbers_2 // numbers_3

array([[[1, 1, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [42]:
numbers_2 / numbers_3

array([[[1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ]],

       [[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]])

In [43]:
#This squares up numbers_2 and put the value into numbers_3

np.square(numbers_2, numbers_3)
numbers_3

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 1,  4,  9],
        [16, 25, 36]]])

In [44]:
deviding_numbers = numbers_2 ** numbers_3

In [45]:
np.mod(numbers_2, numbers_3)

array([[[0, 2, 3],
        [4, 5, 6]],

       [[0, 2, 3],
        [4, 5, 6]]])

## Aggregation

In [46]:
listy_list = [1,2,3,4,5] #Python list
sum(listy_list)

15

In [47]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [48]:
%timeit sum (listy_list) # Python list sum()
%timeit np.sum(listy_list) # Numpy np.sum()

174 ns ± 7.21 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
9.85 μs ± 1.79 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [49]:
numbers_2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.mean(numbers_2)

np.float64(3.5)

In [51]:
# Standard deviation = Measure of how spread out a group of number is from its  mean
np.std (numbers_2)

np.float64(1.707825127659933)

In [52]:
np.var(numbers_2)

np.float64(2.9166666666666665)

In [53]:
# Standard deviation = Square root of variance
np.sqrt(np.var(numbers_2))

np.float64(1.707825127659933)

## Reshape and Transpose
- Reshape changes the shape/structure according to the dimension being specified
- Transpose switches the axis (remember axis 0 = row and axis1 = column)

In [54]:
numbers_2.size

6

In [55]:
numbers_2.shape

(2, 3)

In [56]:
# Reshaping numbers_2

numbers_2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [57]:
# Transpose

numbers_3

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 1,  4,  9],
        [16, 25, 36]]])

In [58]:
numbers_3.shape

(2, 2, 3)

In [59]:
numbers_3.T

array([[[ 1,  1],
        [16, 16]],

       [[ 4,  4],
        [25, 25]],

       [[ 9,  9],
        [36, 36]]])

In [60]:
numbers_3.T.shape

(3, 2, 2)

## Dot product

In [61]:
np.random.seed(10)

mat1 = np.random.randint(10, size=(4,3))
mat2 = np.random.randint(10, size=(4,3))

mat1

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6]], dtype=int32)

In [62]:
mat2

array([[4, 3, 0],
       [4, 6, 8],
       [1, 8, 4],
       [1, 3, 6]], dtype=int32)

In [63]:
# Element-wise Multiplication (Hadamard Product)

mat1*mat2

array([[36, 12,  0],
       [ 4, 54,  0],
       [ 1, 64, 36],
       [ 0, 24, 36]], dtype=int32)

In [64]:
# Dot Product

np.dot(mat1, mat2)

# This code will produce error because the dot product works completely diff from the hadamard product. For Dot product to work the inner shape or dimension of the array must be the same, so we might want to flip axeses for that to work

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [ ]:
#Either reshape or transpose works. so we transpose mat2 to match mat1

mat2.T

array([[4, 4, 1, 1],
       [3, 6, 8, 3],
       [0, 8, 4, 6]], dtype=int32)

In [ ]:
# Dot Product

mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 48,  60,  41,  21],
       [ 31,  58,  73,  28],
       [ 28, 124, 101,  79],
       [ 24,  96,  88,  60]], dtype=int32)

In [ ]:
mat3.shape

(4, 4)

## Dot product example (Nut-butter-sales)

In [83]:
np.random.seed(10)

sales_amount = np.random.randint(20, size = (5,3))
sales_amount

array([[ 9,  4, 15],
       [ 0, 17, 16],
       [17,  8,  9],
       [ 0, 10,  8],
       [ 4, 19, 16]], dtype=int32)

In [88]:

import pandas as pd
weekly_sales = pd.DataFrame (sales_amount, 
                            index = ["Mon", "Tues", "wed", "Thurs", "Fri"],
                            columns = ["Almond butter", "Peanut butter", "Cashew butter"]
                            )
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon                9              4             15
Tues               0             17             16
wed               17              8              9
Thurs              0             10              8
Fri                4             19             16

In [89]:
# Creating array for the price

prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [87]:
prices.shape

(3,)

In [70]:
# Creating prices dataframe

butter_prices = pd.DataFrame(prices.reshape(1,3),
                 index=["Price"],
                 columns = ["Almond butter", "Peanut butter", "Cashew butter"]
                 )
butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [94]:
total_sales = np.dot(prices,sales_amount.T)
total_sales

array([302, 328, 342, 176, 384])

In [74]:
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon                9              4             15
Tues               0             17             16
wed               17              8              9
Thurs              0             10              8
Fri                4             19             16

In [75]:
weekly_sales ["Total($)"] = total_sales
weekly_sales

       Almond butter  Peanut butter  Cashew butter  Total($)
Mon                9              4             15       302
Tues               0             17             16       328
wed               17              8              9       342
Thurs              0             10              8       176
Fri                4             19             16       384

In [77]:
type(total_sales)

numpy.ndarray

## Sorting Arrays

In [112]:
random_arrays = np.random.randint(20, size = (3,5))
random_arrays

array([[ 7, 11,  1,  0, 12],
       [ 5,  4,  7, 18, 12],
       [ 2,  8, 15, 13, 15]], dtype=int32)

In [113]:
random_arrays

array([[ 7, 11,  1,  0, 12],
       [ 5,  4,  7, 18, 12],
       [ 2,  8, 15, 13, 15]], dtype=int32)

In [114]:
np.sort(random_arrays)

array([[ 0,  1,  7, 11, 12],
       [ 4,  5,  7, 12, 18],
       [ 2,  8, 13, 15, 15]], dtype=int32)

In [115]:
np.argsort(random_arrays)

array([[3, 2, 0, 1, 4],
       [1, 0, 2, 4, 3],
       [0, 1, 3, 2, 4]])

In [127]:
np.argmin(random_arrays)

np.int64(3)

In [130]:
np.argmin(random_arrays, axis = 1)

array([3, 1, 0])

In [128]:
np.argmax(random_arrays)

np.int64(8)

## Numpy in action (practical examples)
- Creating arrays from image

<img src="Images/panda.png"/>

In [140]:
## Turning images into Numpy array

from matplotlib.image import imread

panda = imread("images/panda.png")
type(panda)

numpy.ndarray

In [141]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0.05098039, 0.03137255],
        ...,
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]]],
      shape=(2330, 3500, 3), dtype=float32)

In [143]:
panda[:10]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.17254902, 0.13725491, 0.10196079],
        [0.17254902, 0.13725491, 0.10196079],
        [0.17254902, 0.13725491, 0.10196079]],

       [[0.05098039, 0.10196079, 0.0627451 ],
        [0.05098039, 0.10196079, 0.0627451 ],
        [0.05098039, 0.10196079, 0.0627451 ],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05098039, 0.10196079, 0.0627451 ],
        [0.05098039, 0.10196079, 0.0627451 ],
        [0.05098039, 0.10196079, 0.0627451 ],
        ...,
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922]]],
      shape=(10, 3500, 3), dtype=float32)

<img src="images/car-photo.png"/>

In [145]:
car = imread("images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.48235294, 0.3529412 , 1.        ],
        [0.4509804 , 0.49019608, 0.38039216, 1.        ]],

       ...,

       [[0.47058824, 0.57254905, 0.6313726 , 1.        ],
        [0.4392157 , 0.53333336, 0.5882353 , 1.        ],
        [0.48235294, 0.5803922 , 0.6392157 , 1.        ],
        ...,
        [0.6156863 , 0.7529412 , 0.827451  , 1.        ],
        [0.61960787, 0.7607843 , 0.83137256, 1.        ],
        [0.5921569 , 0.73333335, 0.7921569 , 1.        ]],

       [[0.4745098 , 0.5803922 , 0.6392157 , 1.        ],
        [0.47058824, 0.58431375, 0.63529414, 1.        ],
        [0.4117647 , 0.5019608 , 0.5529412 , 1.        ],
        ...,
        [0.54901963, 0.6784314 , 0.74509805, 1.        ],
        [0.65882355, 0.8117647 , 0.8862745 , 1.        ],
        [0.60784316, 0.74509805, 0.8117647 , 1.        ]],

       [[0.4745098 , 0.57254905, 0.627451  , 1.        ],
        [0.49411765, 0.6       , 0.65882355, 1.        ],
        [0.49019608, 0.5921569 , 0.64705884, 1.        ],
        ...,
        [0.5294118 , 0.63529414, 0.69803923, 1.        ],
        [0.5529412 , 0.67058825, 0.7372549 , 1.        ],
        [0.6156863 , 0.73333335, 0.8       , 1.        ]]],
      shape=(431, 575, 4), dtype=float32)

In [146]:
car[:5]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.48235294, 0.3529412 , 1.        ],
        [0.4509804 , 0.49019608, 0.38039216, 1.        ]],

       [[0.40392157, 0.3882353 , 0.36078432, 1.        ],
        [0.41960785, 0.41960785, 0.39607844, 1.        ],
        [0.5137255 , 0.5372549 , 0.50980395, 1.        ],
        ...,
        [0.41568628, 0.41960785, 0.28235295, 1.        ],
        [0.4392157 , 0.4627451 , 0.3019608 , 1.        ],
        [0.48235294, 0.5254902 , 0.37254903, 1.        ]],

       [[0.41568628, 0.40784314, 0.38431373, 1.        ],
        [0.54901963, 0.5647059 , 0.5372549 , 1.        ],
        [0.65882355, 0.7019608 , 0.6627451 , 1.        ],
        ...,
        [0.42745098, 0.41960785, 0.31764707, 1.        ],
        [0.42352942, 0.43137255, 0.29803923, 1.        ],
        [0.4509804 , 0.47843137, 0.32941177, 1.        ]]],
      shape=(5, 575, 4), dtype=float32)

<img src="images/dog-photo.png"/>

In [148]:
dog = imread("images/dog-photo.png")
dog[:5]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.6862745 , 0.84313726, 1.        ],
        [0.49803922, 0.6862745 , 0.84313726, 1.        ]],

       [[0.7058824 , 0.8039216 , 0.8862745 , 1.        ],
        [0.74509805, 0.81960785, 0.8862745 , 1.        ],
        [0.7647059 , 0.83137256, 0.8901961 , 1.        ],
        ...,
        [0.5058824 , 0.69411767, 0.84705883, 1.        ],
        [0.5019608 , 0.6901961 , 0.84705883, 1.        ],
        [0.49803922, 0.6862745 , 0.84705883, 1.        ]],

       [[0.7176471 , 0.80784315, 0.8862745 , 1.        ],
        [0.7411765 , 0.81960785, 0.8862745 , 1.        ],
        [0.77254903, 0.8352941 , 0.89411765, 1.        ],
        ...,
        [0.5137255 , 0.69411767, 0.84313726, 1.        ],
        [0.5058824 , 0.69411767, 0.84313726, 1.        ],
        [0.5019608 , 0.6901961 , 0.84705883, 1.        ]]],
      shape=(5, 575, 4), dtype=float32)

In [149]:
dog.size, dog.shape

(993600, (432, 575, 4))